#pragma config(Sensor, in1,    Right,          sensorLineFollower)
#pragma config(Sensor, in2,    Middle,         sensorLineFollower)
#pragma config(Sensor, in3,    Left,           sensorLineFollower)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftMotor3,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftMotor4,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 55;

task main()
{
	//lift arm slightly
	motor[liftMotor1] = 60;
	motor[liftMotor2] = 60;
	motor[liftMotor3] = 60;
	motor[liftMotor4] = 60;
	wait1Msec(2000);
	motor[liftMotor1] = 0;
	motor[liftMotor2] = 0;
	motor[liftMotor3] = 0;
	motor[liftMotor4] = 0;

	while(SensorValue(Middle) > 40)
	{
		motor[leftMotor] = 120;
   	motor[rightMotor] = 120;


  }
  //while(encoderCount < 500){
  // RIGHT sensor sees dark:
    if(SensorValue(Right) < threshold)
    {
      // counter-steer right:
      motor[leftMotor]  = 63;
      motor[rightMotor] = 0;
    }
    // CENTER sensor sees dark:
    if(SensorValue(Middle) < threshold)
    {
      // go straight
      motor[leftMotor]  = 63;
      motor[rightMotor] = 63;
    }
    // LEFT sensor sees dark:
    if(SensorValue(Left) < threshold)
    {
      // counter-steer left:
      motor[leftMotor]  = 0;
      motor[rightMotor] = 63;
    }
//} end encoder count down

}



